<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-33E9QT3" failures="1" tests="2" name="Regression Parallel EDGE" time="29.357" errors="0" timestamp="2023-09-17T11:10:36 ICT">
  <testcase classname="BinhAT.testcases.LoginTest" name="loginTestFromDataproviderExcelCustomRow" time="9.723">
    <failure type="java.lang.AssertionError" message="Login không thành công expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login không thành công expected [true] but found [false]
at BinhAT.pages.LoginPage.login(LoginPage.java:60)
at BinhAT.testcases.LoginTest.loginTestFromDataproviderExcelCustomRow(LoginTest.java:72)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- loginTestFromDataproviderExcelCustomRow -->
  <testcase classname="BinhAT.testcases.LoginTest" name="loginTestFromDataproviderExcelCustomRow" time="19.09"/>
  <testcase classname="BinhAT.testcases.LoginTest" name="loginTestFromDataproviderExcel" time="0.0">
    <ignored/>
  </testcase> <!-- loginTestFromDataproviderExcel -->
  <testcase classname="BinhAT.testcases.LoginTest" name="loginTestSuccess" time="0.0">
    <ignored/>
  </testcase> <!-- loginTestSuccess -->
  <testcase classname="BinhAT.testcases.LoginTest" name="loginTestInvalidEmail" time="0.0">
    <ignored/>
  </testcase> <!-- loginTestInvalidEmail -->
</testsuite> <!-- Regression Parallel EDGE -->
